package at.erp.light.view.model;

// Generated 22.11.2014 18:02:50 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Address generated by hbm2java
 */
@Entity
@Table(name = "address", schema = "public")
public class Address implements java.io.Serializable {

	private int addressId;
	
	@Column(unique = true)
	private String address;

	public Address() {
	}

	public Address(int addressId, String address) {
		this.addressId = addressId;
		this.address = address;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="gen_address_id")
	@SequenceGenerator(name="gen_address_id", sequenceName="address_address_id_seq", allocationSize=1)
	@Column(name = "address_id", unique = true, nullable = false)
	public int getAddressId() {
		return this.addressId;
	}

	public void setAddressId(int addressId) {
		this.addressId = addressId;
	}

	@Column(name = "address", nullable = false, length = 100)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

}
