package at.erp.light.view.model;

// Generated 22.11.2014 18:02:50 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * City generated by hbm2java
 */
@Entity
@Table(name = "city", schema = "public")
public class City implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8172561998275025321L;
	private int cityId;
	private String zip;
	private String city;
	private Set<Organisation> organisations = new HashSet<Organisation>(0);
	private Set<Person> persons = new HashSet<Person>(0);

	public City() {
	}

	public City(int cityId, String city, String zip) {
		this.cityId = cityId;
		this.zip = zip;
		this.city = city;
	}

	public City(int cityId, String city, String zip,
			Set<Organisation> organisations, Set<Person> persons) {
		this.cityId = cityId;
		this.zip = zip;
		this.city = city;
		this.organisations = organisations;
		this.persons = persons;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="gen_city_id")
	@SequenceGenerator(name="gen_city_id", sequenceName="city_city_id_seq", allocationSize=1)
	@Column(name = "city_id", unique = true, nullable = false)
	public int getCityId() {
		return this.cityId;
	}

	public void setCityId(int cityId) {
		this.cityId = cityId;
	}

	@Column(name = "zip", nullable = false, length = 5)
	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	@Column(name = "city", nullable = false, length = 100)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "city")
	public Set<Organisation> getOrganisations() {
		return this.organisations;
	}

	public void setOrganisations(Set<Organisation> organisations) {
		this.organisations = organisations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "city")
	public Set<Person> getPersons() {
		return this.persons;
	}

	public void setPersons(Set<Person> persons) {
		this.persons = persons;
	}

}
