package at.erp.light.view.model;

// Generated 22.11.2014 18:02:50 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * IncomingArticle generated by hbm2java
 */
@Entity
@Table(name = "incoming_article", schema = "public")
public class IncomingArticle implements java.io.Serializable {

	private int incomingArticleId;
	private Article article;
	private IncomingDelivery incomingDelivery;
	private Integer articleNr;	// used for order within an incomingDelivery
	private Double numberpu;

	public IncomingArticle() {
	}

	public IncomingArticle(int incomingArticleId, IncomingDelivery incomingDelivery,
			Article article, Integer articleNr, Double numberpu) {
		this.incomingArticleId = incomingArticleId;
		this.incomingDelivery = incomingDelivery;
		this.article = article;
		this.articleNr = articleNr;
		this.numberpu = numberpu;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="gen_incoming_article_id")
	@SequenceGenerator(name="gen_incoming_article_id", sequenceName="incoming_article_incoming_article_id_seq", allocationSize=1)
	@Column(name = "incoming_article_id", unique = true, nullable = false)
	public int getIncomingArticleId() {
		return this.incomingArticleId;
	}

	public void setIncomingArticleId(int incomingArticleId) {
		this.incomingArticleId = incomingArticleId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "article_id", nullable = false)
	public Article getArticle() {
		return this.article;
	}

	public void setArticle(Article article) {
		this.article = article;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "incoming_delivery_id", nullable = false)
	public IncomingDelivery getIncomingDelivery() {
		return this.incomingDelivery;
	}


	public void setIncomingDelivery(IncomingDelivery incomingDelivery) {
		this.incomingDelivery = incomingDelivery;
	}


	@Column(name = "article_nr")
	public Integer getArticleNr() {
		return this.articleNr;
	}

	public void setArticleNr(Integer articleNr) {
		this.articleNr = articleNr;
	}

	@Column(name = "numberpu", precision = 17, scale = 17)
	public Double getNumberpu() {
		return this.numberpu;
	}

	public void setNumberpu(Double numberpu) {
		this.numberpu = numberpu;
	}

}
