package at.erp.light.view.model;

// Generated 22.11.2014 18:02:50 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IncomingDelivery generated by hbm2java
 */
@Entity
@Table(name = "incoming_delivery", schema = "public")
public class IncomingDelivery implements java.io.Serializable {

	private int incomingDeliveryId;
	private Organisation organisation;
	private Person lastEditor;
	private Integer deliveryNr;
	private Date date;
	private String comment;
	private Set<IncomingArticle> incomingArticles = new HashSet<IncomingArticle>(
			0);

	public IncomingDelivery() {
	}

	public IncomingDelivery(int incomingDeliveryId, Organisation organisation,
			Person lastEditor, Date date, String comment) {
		this.incomingDeliveryId = incomingDeliveryId;
		this.organisation = organisation;
		this.lastEditor = lastEditor;
		this.date = date;
		this.comment = comment;
	}

	public IncomingDelivery(int incomingDeliveryId, Organisation organisation,
			Person lastEditor, Integer deliveryNr, Date date, String comment,
			Set<IncomingArticle> incomingArticles) {
		this.incomingDeliveryId = incomingDeliveryId;
		this.organisation = organisation;
		this.lastEditor = lastEditor;
		this.deliveryNr = deliveryNr;
		this.date = date;
		this.comment = comment;
		this.incomingArticles = incomingArticles;
	}

	@Id
	@Column(name = "incoming_delivery_id", unique = true, nullable = false)
	public int getIncomingDeliveryId() {
		return this.incomingDeliveryId;
	}

	public void setIncomingDeliveryId(int incomingDeliveryId) {
		this.incomingDeliveryId = incomingDeliveryId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "organisation_id", nullable = false)
	public Organisation getOrganisation() {
		return this.organisation;
	}

	public void setOrganisation(Organisation organisation) {
		this.organisation = organisation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "person_id", nullable = false)
	public Person getLastEditor() {
		return this.lastEditor;
	}

	public void setLastEditor(Person lastEditor) {
		this.lastEditor = lastEditor;
	}

	@Column(name = "delivery_nr")
	public Integer getDeliveryNr() {
		return this.deliveryNr;
	}

	public void setDeliveryNr(Integer deliveryNr) {
		this.deliveryNr = deliveryNr;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", nullable = false, length = 13)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "comment", nullable = false, length = 1000)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "incomingDelivery")
	public Set<IncomingArticle> getIncomingArticles() {
		return this.incomingArticles;
	}

	public void setIncomingArticles(Set<IncomingArticle> incomingArticles) {
		this.incomingArticles = incomingArticles;
	}

}
