package at.erp.light.view.model;

// Generated 22.11.2014 18:02:50 by Hibernate Tools 3.4.0.CR1

import java.sql.Timestamp;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Logging generated by hbm2java
 */
@Entity
@Table(name = "logging", schema = "public")
public class Logging implements java.io.Serializable {

	private int loggingId;
	private String loggingtext;
	private Timestamp timestamp;
	private int personId;

	public Logging() {
	}

	public Logging(int loggingId, Timestamp timestamp, String loggingtext, int personId) {
		this.loggingId = loggingId;
		this.loggingtext = loggingtext;
		this.timestamp = timestamp;
		this.personId = personId;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="gen_logging_id")
	@SequenceGenerator(name="gen_logging_id", sequenceName="logging_logging_id_seq", allocationSize=1)
	@Column(name = "logging_id", unique = true, nullable = false)
	public int getLoggingId() {
		return this.loggingId;
	}

	public void setLoggingId(int loggingId) {
		this.loggingId = loggingId;
	}

	@Column(name = "loggingtext", nullable = false, length = 1000)
	public String getLoggingtext() {
		return this.loggingtext;
	}

	public void setLoggingtext(String loggingtext) {
		this.loggingtext = loggingtext;
	}
	
	@Column(name = "timestamp", nullable = false)
	public Timestamp getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Timestamp timestamp) {
		this.timestamp = timestamp;
	}
	
	@Column(name = "person_id")
	public int getPersonId() {
		return this.personId;
	}

	public void setPersonId(int personId) {
		this.personId = personId;
	}

}
