package at.erp.light.view.model;

// Generated 22.11.2014 18:02:50 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Permission generated by hbm2java
 */
@Entity
@Table(name = "permission", schema = "public")
public class Permission implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1046312663440017806L;
	public static int ADMIN = 1;
	public static int READWRITE = 2;
	public static int READ = 3;	
	
	private int permissionId;
	private String permission;
	private String description;

	public Permission() {
	}

	public Permission(int permissionId, String permission, String description) {
		this.permissionId = permissionId;
		this.permission = permission;
		this.description = description;
	}

	@Id
	@Column(name = "permission_id", unique = true, nullable = false)
	public int getPermissionId() {
		return this.permissionId;
	}

	public void setPermissionId(int permissionId) {
		this.permissionId = permissionId;
	}

	@Column(name = "permission", nullable = false)
	public String getPermission() {
		return this.permission;
	}

	public void setPermission(String permission) {
		this.permission = permission;
	}

	@Column(name = "description", length = 1024)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
