package at.erp.light.view.model;

// Generated 03.12.2014 13:09:29 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Telephone generated by hbm2java
 */
@Entity
@Table(name = "telephone", schema = "public")
public class Telephone implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6291602797114207566L;
	private int telephoneId;
	// private Person person;
	private Type type;
	private String telephone;

	public Telephone() {
	}

	public Telephone(int telephoneId, Type type, String telephone) {
		this.telephoneId = telephoneId;
		this.type = type;
		this.telephone = telephone;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="gen_telephone_id")
	@SequenceGenerator(name="gen_telephone_id", sequenceName="telephone_telephone_id_seq", allocationSize=1)
	@Column(name = "telephone_id", unique = true, nullable = false)
	public int getTelephoneId() {
		return this.telephoneId;
	}

	public void setTelephoneId(int telephoneId) {
		this.telephoneId = telephoneId;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "type_id", nullable = false)
	public Type getType() {
		return this.type;
	}

	public void setType(Type type) {
		this.type = type;
	}

	@Column(name = "telephone", nullable = false, length = 20)
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

}
