package at.erp.light.view.model;

// Generated 03.12.2014 12:48:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Telephone generated by hbm2java
 */
@Entity
@Table(name = "telephone", schema = "public")
public class Telephone implements java.io.Serializable {

	private int telephoneId;
	private Integer personId;
	private int typeId;
	private String telephone;

	public Telephone() {
	}

	public Telephone(int telephoneId, int typeId, String telephone) {
		this.telephoneId = telephoneId;
		this.typeId = typeId;
		this.telephone = telephone;
	}

	public Telephone(int telephoneId, Integer personId, int typeId,
			String telephone) {
		this.telephoneId = telephoneId;
		this.personId = personId;
		this.typeId = typeId;
		this.telephone = telephone;
	}

	@Id
	@Column(name = "telephone_id", unique = true, nullable = false)
	public int getTelephoneId() {
		return this.telephoneId;
	}

	public void setTelephoneId(int telephoneId) {
		this.telephoneId = telephoneId;
	}

	@Column(name = "person_id")
	public Integer getPersonId() {
		return this.personId;
	}

	public void setPersonId(Integer personId) {
		this.personId = personId;
	}

	@Column(name = "type_id", nullable = false)
	public int getTypeId() {
		return this.typeId;
	}

	public void setTypeId(int typeId) {
		this.typeId = typeId;
	}

	@Column(name = "telephone", nullable = false, length = 20)
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

}
