package at.erplight.model;

// Generated 22.11.2014 18:02:50 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Address generated by hbm2java
 */
@Entity
@Table(name = "address", schema = "public")
public class Address implements java.io.Serializable {

	private int addressId;
	private String address;
	private Set<Person> persons = new HashSet<Person>(0);
	private Set<Organisation> organisations = new HashSet<Organisation>(0);

	public Address() {
	}

	public Address(int addressId, String address) {
		this.addressId = addressId;
		this.address = address;
	}

	public Address(int addressId, String address, Set<Person> persons,
			Set<Organisation> organisations) {
		this.addressId = addressId;
		this.address = address;
		this.persons = persons;
		this.organisations = organisations;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="gen_address_id")
	@SequenceGenerator(name="gen_address_id", sequenceName="address_address_id_seq", allocationSize=1)
	@Column(name = "address_id", unique = true, nullable = false)
	public int getAddressId() {
		return this.addressId;
	}

	public void setAddressId(int addressId) {
		this.addressId = addressId;
	}

	@Column(name = "address", nullable = false, length = 100)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "address")
	public Set<Person> getPersons() {
		return this.persons;
	}

	public void setPersons(Set<Person> persons) {
		this.persons = persons;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "address")
	public Set<Organisation> getOrganisations() {
		return this.organisations;
	}

	public void setOrganisations(Set<Organisation> organisations) {
		this.organisations = organisations;
	}

}
