package at.erplight.model;

// Generated 14.11.2014 00:05:19 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Adresse generated by hbm2java
 */
@Entity
@Table(name = "adresse", schema = "public")
public class Adresse implements java.io.Serializable {

	private int adresseId;
	private String adresse;
	private Set<Person> persons = new HashSet<Person>(0);
	private Set<Organisation> organisations = new HashSet<Organisation>(0);

	public Adresse() {
	}

	public Adresse(int adresseId, String adresse) {
		this.adresseId = adresseId;
		this.adresse = adresse;
	}

	public Adresse(int adresseId, String adresse, Set<Person> persons,
			Set<Organisation> organisations) {
		this.adresseId = adresseId;
		this.adresse = adresse;
		this.persons = persons;
		this.organisations = organisations;
	}

	@Id
	@Column(name = "adresse_id", unique = true, nullable = false)
	public int getAdresseId() {
		return this.adresseId;
	}

	public void setAdresseId(int adresseId) {
		this.adresseId = adresseId;
	}

	@Column(name = "adresse", nullable = false, length = 100)
	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "adresse")
	public Set<Person> getPersons() {
		return this.persons;
	}

	public void setPersons(Set<Person> persons) {
		this.persons = persons;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "adresse")
	public Set<Organisation> getOrganisations() {
		return this.organisations;
	}

	public void setOrganisations(Set<Organisation> organisations) {
		this.organisations = organisations;
	}

}
