package at.erplight.model;

// Generated 13.11.2014 22:13:18 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EingangsLieferung generated by hbm2java
 */
@Entity
@Table(name = "eingangs_lieferung", schema = "public")
public class EingangsLieferung implements java.io.Serializable {

	private int lieferEinId;
	private Organisation organisation;
	private Person person;
	private Integer liefernr;
	private Date datum;
	private String bemerkung;
	private Set<Wareneingang> wareneingangs = new HashSet<Wareneingang>(0);

	public EingangsLieferung() {
	}

	public EingangsLieferung(int lieferEinId, Organisation organisation,
			Person person, Date datum, String bemerkung) {
		this.lieferEinId = lieferEinId;
		this.organisation = organisation;
		this.person = person;
		this.datum = datum;
		this.bemerkung = bemerkung;
	}

	public EingangsLieferung(int lieferEinId, Organisation organisation,
			Person person, Integer liefernr, Date datum, String bemerkung,
			Set<Wareneingang> wareneingangs) {
		this.lieferEinId = lieferEinId;
		this.organisation = organisation;
		this.person = person;
		this.liefernr = liefernr;
		this.datum = datum;
		this.bemerkung = bemerkung;
		this.wareneingangs = wareneingangs;
	}

	@Id
	@Column(name = "liefer_ein_id", unique = true, nullable = false)
	public int getLieferEinId() {
		return this.lieferEinId;
	}

	public void setLieferEinId(int lieferEinId) {
		this.lieferEinId = lieferEinId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "org_id", nullable = false)
	public Organisation getOrganisation() {
		return this.organisation;
	}

	public void setOrganisation(Organisation organisation) {
		this.organisation = organisation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "person_id", nullable = false)
	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	@Column(name = "liefernr_")
	public Integer getLiefernr() {
		return this.liefernr;
	}

	public void setLiefernr(Integer liefernr) {
		this.liefernr = liefernr;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "datum", nullable = false, length = 13)
	public Date getDatum() {
		return this.datum;
	}

	public void setDatum(Date datum) {
		this.datum = datum;
	}

	@Column(name = "bemerkung", nullable = false, length = 1000)
	public String getBemerkung() {
		return this.bemerkung;
	}

	public void setBemerkung(String bemerkung) {
		this.bemerkung = bemerkung;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "eingangsLieferung")
	public Set<Wareneingang> getWareneingangs() {
		return this.wareneingangs;
	}

	public void setWareneingangs(Set<Wareneingang> wareneingangs) {
		this.wareneingangs = wareneingangs;
	}

}
