package at.erplight.model;

// Generated 13.11.2014 22:13:18 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Email generated by hbm2java
 */
@Entity
@Table(name = "email", schema = "public")
public class Email implements java.io.Serializable {

	private int emailId;
	private String email;
	private Set<Person> persons = new HashSet<Person>(0);

	public Email() {
	}

	public Email(int emailId, String email) {
		this.emailId = emailId;
		this.email = email;
	}

	public Email(int emailId, String email, Set<Person> persons) {
		this.emailId = emailId;
		this.email = email;
		this.persons = persons;
	}

	@Id
	@Column(name = "email_id", unique = true, nullable = false)
	public int getEmailId() {
		return this.emailId;
	}

	public void setEmailId(int emailId) {
		this.emailId = emailId;
	}

	@Column(name = "email", nullable = false, length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "emails")
	public Set<Person> getPersons() {
		return this.persons;
	}

	public void setPersons(Set<Person> persons) {
		this.persons = persons;
	}

}
