package at.erplight.model;

// Generated 21.11.2014 00:35:55 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Email generated by hbm2java
 */
@Entity
@Table(name = "email", schema = "public")
public class Email implements java.io.Serializable {

	private int emailId;
	private Person person;
	private String loginEmail;
	private int type;

	public Email() {
	}

	public Email(int emailId, String loginEmail, int type) {
		this.emailId = emailId;
		this.loginEmail = loginEmail;
		this.type = type;
	}

	public Email(int emailId, Person person, String loginEmail, int type) {
		this.emailId = emailId;
		this.person = person;
		this.loginEmail = loginEmail;
		this.type = type;
	}

	@Id
	@Column(name = "email_id", unique = true, nullable = false)
	public int getEmailId() {
		return this.emailId;
	}

	public void setEmailId(int emailId) {
		this.emailId = emailId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "person_id")
	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	@Column(name = "login_email", nullable = false, length = 50)
	public String getLoginEmail() {
		return this.loginEmail;
	}

	public void setLoginEmail(String loginEmail) {
		this.loginEmail = loginEmail;
	}

	@Column(name = "type", nullable = false)
	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

}
