package at.erplight.model;

// Generated 14.11.2014 00:05:19 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Land generated by hbm2java
 */
@Entity
@Table(name = "land", schema = "public")
public class Land implements java.io.Serializable {

	private int landId;
	private String land;
	private Set<Organisation> organisations = new HashSet<Organisation>(0);
	private Set<Person> persons = new HashSet<Person>(0);

	public Land() {
	}

	public Land(int landId, String land) {
		this.landId = landId;
		this.land = land;
	}

	public Land(int landId, String land, Set<Organisation> organisations,
			Set<Person> persons) {
		this.landId = landId;
		this.land = land;
		this.organisations = organisations;
		this.persons = persons;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="land_seq")
	@SequenceGenerator(name="land_seq", sequenceName="land_land_id_seq", allocationSize=1)
	@Column(name = "land_id", unique = true, nullable = false)
	public int getLandId() {
		return this.landId;
	}

	public void setLandId(int landId) {
		this.landId = landId;
	}

	@Column(name = "land", nullable = false, length = 50)
	public String getLand() {
		return this.land;
	}

	public void setLand(String land) {
		this.land = land;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "land")
	public Set<Organisation> getOrganisations() {
		return this.organisations;
	}

	public void setOrganisations(Set<Organisation> organisations) {
		this.organisations = organisations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "land")
	public Set<Person> getPersons() {
		return this.persons;
	}

	public void setPersons(Set<Person> persons) {
		this.persons = persons;
	}

}
