package at.erplight.model;

// Generated 22.11.2014 18:02:50 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Logging generated by hbm2java
 */
@Entity
@Table(name = "logging", schema = "public")
public class Logging implements java.io.Serializable {

	private int loggingId;
	private String loggingtext;

	public Logging() {
	}

	public Logging(int loggingId, String loggingtext) {
		this.loggingId = loggingId;
		this.loggingtext = loggingtext;
	}

	@Id
	@Column(name = "logging_id", unique = true, nullable = false)
	public int getLoggingId() {
		return this.loggingId;
	}

	public void setLoggingId(int loggingId) {
		this.loggingId = loggingId;
	}

	@Column(name = "loggingtext", nullable = false, length = 1000)
	public String getLoggingtext() {
		return this.loggingtext;
	}

	public void setLoggingtext(String loggingtext) {
		this.loggingtext = loggingtext;
	}

}
