package at.erplight.model;

// Generated 14.11.2014 00:05:19 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ort generated by hbm2java
 */
@Entity
@Table(name = "ort", schema = "public")
public class Ort implements java.io.Serializable {

	private int ortId;
	private String plz;
	private String ort;
	private Set<Person> persons = new HashSet<Person>(0);
	private Set<Organisation> organisations = new HashSet<Organisation>(0);

	public Ort() {
	}

	public Ort(int ortId, String plz, String ort) {
		this.ortId = ortId;
		this.plz = plz;
		this.ort = ort;
	}

	public Ort(int ortId, String plz, String ort, Set<Person> persons,
			Set<Organisation> organisations) {
		this.ortId = ortId;
		this.plz = plz;
		this.ort = ort;
		this.persons = persons;
		this.organisations = organisations;
	}

	@Id
	@Column(name = "ort_id", unique = true, nullable = false)
	public int getOrtId() {
		return this.ortId;
	}

	public void setOrtId(int ortId) {
		this.ortId = ortId;
	}

	@Column(name = "plz", nullable = false, length = 5)
	public String getPlz() {
		return this.plz;
	}

	public void setPlz(String plz) {
		this.plz = plz;
	}

	@Column(name = "ort", nullable = false, length = 100)
	public String getOrt() {
		return this.ort;
	}

	public void setOrt(String ort) {
		this.ort = ort;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ort")
	public Set<Person> getPersons() {
		return this.persons;
	}

	public void setPersons(Set<Person> persons) {
		this.persons = persons;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ort")
	public Set<Organisation> getOrganisations() {
		return this.organisations;
	}

	public void setOrganisations(Set<Organisation> organisations) {
		this.organisations = organisations;
	}

}
