package at.erplight.model;

// Generated 22.11.2014 18:02:50 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OutgoingArticle generated by hbm2java
 */
@Entity
@Table(name = "outgoing_article", schema = "public")
public class OutgoingArticle implements java.io.Serializable {

	private int outgoingArticleId;
	private OutgoingDelivery outgoingDelivery;
	private Article article;
	private Integer articleNr;
	private Double numberpu;

	public OutgoingArticle() {
	}

	public OutgoingArticle(int outgoingArticleId,
			OutgoingDelivery outgoingDelivery, Article article) {
		this.outgoingArticleId = outgoingArticleId;
		this.outgoingDelivery = outgoingDelivery;
		this.article = article;
	}

	public OutgoingArticle(int outgoingArticleId,
			OutgoingDelivery outgoingDelivery, Article article,
			Integer articleNr, Double numberpu) {
		this.outgoingArticleId = outgoingArticleId;
		this.outgoingDelivery = outgoingDelivery;
		this.article = article;
		this.articleNr = articleNr;
		this.numberpu = numberpu;
	}

	@Id
	@Column(name = "outgoing_article_id", unique = true, nullable = false)
	public int getOutgoingArticleId() {
		return this.outgoingArticleId;
	}

	public void setOutgoingArticleId(int outgoingArticleId) {
		this.outgoingArticleId = outgoingArticleId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "outgoing_delivery_id", nullable = false)
	public OutgoingDelivery getOutgoingDelivery() {
		return this.outgoingDelivery;
	}

	public void setOutgoingDelivery(OutgoingDelivery outgoingDelivery) {
		this.outgoingDelivery = outgoingDelivery;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "article_id", nullable = false)
	public Article getArticle() {
		return this.article;
	}

	public void setArticle(Article article) {
		this.article = article;
	}

	@Column(name = "article_nr")
	public Integer getArticleNr() {
		return this.articleNr;
	}

	public void setArticleNr(Integer articleNr) {
		this.articleNr = articleNr;
	}

	@Column(name = "numberpu", precision = 17, scale = 17)
	public Double getNumberpu() {
		return this.numberpu;
	}

	public void setNumberpu(Double numberpu) {
		this.numberpu = numberpu;
	}

}
