package at.erplight.model;

// Generated 22.11.2014 18:02:50 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Permission generated by hbm2java
 */
@Entity
@Table(name = "permission", schema = "public")
public class Permission implements java.io.Serializable {

	private int permissionId;
	private int permission;
	private String description;
	private Set<Platformuser> platformusers = new HashSet<Platformuser>(0);

	public Permission() {
	}

	public Permission(int permissionId, int permission, String description) {
		this.permissionId = permissionId;
		this.permission = permission;
		this.description = description;
	}

	public Permission(int permissionId, int permission, String description,
			Set<Platformuser> platformusers) {
		this.permissionId = permissionId;
		this.permission = permission;
		this.description = description;
		this.platformusers = platformusers;
	}

	@Id
	@Column(name = "permission_id", unique = true, nullable = false)
	public int getPermissionId() {
		return this.permissionId;
	}

	public void setPermissionId(int permissionId) {
		this.permissionId = permissionId;
	}

	@Column(name = "permission", nullable = false)
	public int getPermission() {
		return this.permission;
	}

	public void setPermission(int permission) {
		this.permission = permission;
	}

	@Column(name = "description", nullable = false, length = 1024)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "permission")
	public Set<Platformuser> getPlatformusers() {
		return this.platformusers;
	}

	public void setPlatformusers(Set<Platformuser> platformusers) {
		this.platformusers = platformusers;
	}

}
