package at.erplight.model;

// Generated 14.11.2014 00:05:19 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Rechte generated by hbm2java
 */
@Entity
@Table(name = "rechte", schema = "public")
public class Rechte implements java.io.Serializable {

	private int rechteId;
	private int rechte;
	private String beschreibung;
	private Set<Person> persons = new HashSet<Person>(0);

	public Rechte() {
	}

	public Rechte(int rechteId, int rechte, String beschreibung) {
		this.rechteId = rechteId;
		this.rechte = rechte;
		this.beschreibung = beschreibung;
	}

	public Rechte(int rechteId, int rechte, String beschreibung,
			Set<Person> persons) {
		this.rechteId = rechteId;
		this.rechte = rechte;
		this.beschreibung = beschreibung;
		this.persons = persons;
	}

	@Id
	@Column(name = "rechte_id", unique = true, nullable = false)
	public int getRechteId() {
		return this.rechteId;
	}

	public void setRechteId(int rechteId) {
		this.rechteId = rechteId;
	}

	@Column(name = "rechte", nullable = false)
	public int getRechte() {
		return this.rechte;
	}

	public void setRechte(int rechte) {
		this.rechte = rechte;
	}

	@Column(name = "beschreibung", nullable = false, length = 1024)
	public String getBeschreibung() {
		return this.beschreibung;
	}

	public void setBeschreibung(String beschreibung) {
		this.beschreibung = beschreibung;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rechte")
	public Set<Person> getPersons() {
		return this.persons;
	}

	public void setPersons(Set<Person> persons) {
		this.persons = persons;
	}

}
