package at.erplight.model;

// Generated 13.11.2014 22:13:18 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Reporting generated by hbm2java
 */
@Entity
@Table(name = "reporting", schema = "public")
public class Reporting implements java.io.Serializable {

	private int reportId;
	private Date datum;
	private String beschreibung;
	private Character reportfile;

	public Reporting() {
	}

	public Reporting(int reportId, Date datum) {
		this.reportId = reportId;
		this.datum = datum;
	}

	public Reporting(int reportId, Date datum, String beschreibung,
			Character reportfile) {
		this.reportId = reportId;
		this.datum = datum;
		this.beschreibung = beschreibung;
		this.reportfile = reportfile;
	}

	@Id
	@Column(name = "report_id", unique = true, nullable = false)
	public int getReportId() {
		return this.reportId;
	}

	public void setReportId(int reportId) {
		this.reportId = reportId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "datum", nullable = false, length = 13)
	public Date getDatum() {
		return this.datum;
	}

	public void setDatum(Date datum) {
		this.datum = datum;
	}

	@Column(name = "beschreibung", length = 1024)
	public String getBeschreibung() {
		return this.beschreibung;
	}

	public void setBeschreibung(String beschreibung) {
		this.beschreibung = beschreibung;
	}

	@Column(name = "reportfile", length = 1)
	public Character getReportfile() {
		return this.reportfile;
	}

	public void setReportfile(Character reportfile) {
		this.reportfile = reportfile;
	}

}
