package at.erplight.model;

// Generated 22.11.2014 18:02:50 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Telefone generated by hbm2java
 */
@Entity
@Table(name = "telefone", schema = "public")
public class Telefone implements java.io.Serializable {

	private int telefoneId;
	private Type type;
	private Person person;
	private String telefone;

	public Telefone() {
	}

	public Telefone(int telefoneId, Type type, String telefone) {
		this.telefoneId = telefoneId;
		this.type = type;
		this.telefone = telefone;
	}

	public Telefone(int telefoneId, Type type, Person person, String telefone) {
		this.telefoneId = telefoneId;
		this.type = type;
		this.person = person;
		this.telefone = telefone;
	}

	@Id
	@Column(name = "telefone_id", unique = true, nullable = false)
	public int getTelefoneId() {
		return this.telefoneId;
	}

	public void setTelefoneId(int telefoneId) {
		this.telefoneId = telefoneId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "type_id", nullable = false)
	public Type getType() {
		return this.type;
	}

	public void setType(Type type) {
		this.type = type;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "person_id")
	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	@Column(name = "telefone", nullable = false, length = 20)
	public String getTelefone() {
		return this.telefone;
	}

	public void setTelefone(String telefone) {
		this.telefone = telefone;
	}

}
