package at.erplight.model;

// Generated 13.11.2014 22:13:18 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Telefon generated by hbm2java
 */
@Entity
@Table(name = "telefon", schema = "public")
public class Telefon implements java.io.Serializable {

	private int telefonId;
	private String telefon;
	private Set<Person> persons = new HashSet<Person>(0);

	public Telefon() {
	}

	public Telefon(int telefonId, String telefon) {
		this.telefonId = telefonId;
		this.telefon = telefon;
	}

	public Telefon(int telefonId, String telefon, Set<Person> persons) {
		this.telefonId = telefonId;
		this.telefon = telefon;
		this.persons = persons;
	}

	@Id
	@Column(name = "telefon_id", unique = true, nullable = false)
	public int getTelefonId() {
		return this.telefonId;
	}

	public void setTelefonId(int telefonId) {
		this.telefonId = telefonId;
	}

	@Column(name = "telefon", nullable = false, length = 20)
	public String getTelefon() {
		return this.telefon;
	}

	public void setTelefon(String telefon) {
		this.telefon = telefon;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "telefons")
	public Set<Person> getPersons() {
		return this.persons;
	}

	public void setPersons(Set<Person> persons) {
		this.persons = persons;
	}

}
