package at.erplight.model;

// Generated 14.11.2014 00:05:19 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Typ generated by hbm2java
 */
@Entity
@Table(name = "typ", schema = "public")
public class Typ implements java.io.Serializable {

	private int typId;
	private String typname;
	private Set<Organisation> organisations = new HashSet<Organisation>(0);
	private Set<Person> persons = new HashSet<Person>(0);

	public Typ() {
	}

	public Typ(int typId, String typname) {
		this.typId = typId;
		this.typname = typname;
	}

	public Typ(int typId, String typname, Set<Organisation> organisations,
			Set<Person> persons) {
		this.typId = typId;
		this.typname = typname;
		this.organisations = organisations;
		this.persons = persons;
	}

	@Id
	@Column(name = "typ_id", unique = true, nullable = false)
	public int getTypId() {
		return this.typId;
	}

	public void setTypId(int typId) {
		this.typId = typId;
	}

	@Column(name = "typname", nullable = false, length = 100)
	public String getTypname() {
		return this.typname;
	}

	public void setTypname(String typname) {
		this.typname = typname;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "typ")
	public Set<Organisation> getOrganisations() {
		return this.organisations;
	}

	public void setOrganisations(Set<Organisation> organisations) {
		this.organisations = organisations;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "typs")
	public Set<Person> getPersons() {
		return this.persons;
	}

	public void setPersons(Set<Person> persons) {
		this.persons = persons;
	}

}
