package at.erplight.model;

// Generated 13.11.2014 22:13:18 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Waren generated by hbm2java
 */
@Entity
@Table(name = "waren", schema = "public")
public class Waren implements java.io.Serializable {

	private int warenId;
	private String verpackungseinheit;
	private double einzelgewichtDerVe;
	private Date mindesthaltbarkeitsdatum;
	private double einzelpreisEinerVe;
	private Set<Warenausgang> warenausgangs = new HashSet<Warenausgang>(0);
	private Set<Wareneingang> wareneingangs = new HashSet<Wareneingang>(0);

	public Waren() {
	}

	public Waren(int warenId, String verpackungseinheit,
			double einzelgewichtDerVe, Date mindesthaltbarkeitsdatum,
			double einzelpreisEinerVe) {
		this.warenId = warenId;
		this.verpackungseinheit = verpackungseinheit;
		this.einzelgewichtDerVe = einzelgewichtDerVe;
		this.mindesthaltbarkeitsdatum = mindesthaltbarkeitsdatum;
		this.einzelpreisEinerVe = einzelpreisEinerVe;
	}

	public Waren(int warenId, String verpackungseinheit,
			double einzelgewichtDerVe, Date mindesthaltbarkeitsdatum,
			double einzelpreisEinerVe, Set<Warenausgang> warenausgangs,
			Set<Wareneingang> wareneingangs) {
		this.warenId = warenId;
		this.verpackungseinheit = verpackungseinheit;
		this.einzelgewichtDerVe = einzelgewichtDerVe;
		this.mindesthaltbarkeitsdatum = mindesthaltbarkeitsdatum;
		this.einzelpreisEinerVe = einzelpreisEinerVe;
		this.warenausgangs = warenausgangs;
		this.wareneingangs = wareneingangs;
	}

	@Id
	@Column(name = "waren_id", unique = true, nullable = false)
	public int getWarenId() {
		return this.warenId;
	}

	public void setWarenId(int warenId) {
		this.warenId = warenId;
	}

	@Column(name = "verpackungseinheit", nullable = false, length = 100)
	public String getVerpackungseinheit() {
		return this.verpackungseinheit;
	}

	public void setVerpackungseinheit(String verpackungseinheit) {
		this.verpackungseinheit = verpackungseinheit;
	}

	@Column(name = "einzelgewicht_der_ve", nullable = false, precision = 17, scale = 17)
	public double getEinzelgewichtDerVe() {
		return this.einzelgewichtDerVe;
	}

	public void setEinzelgewichtDerVe(double einzelgewichtDerVe) {
		this.einzelgewichtDerVe = einzelgewichtDerVe;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "mindesthaltbarkeitsdatum", nullable = false, length = 13)
	public Date getMindesthaltbarkeitsdatum() {
		return this.mindesthaltbarkeitsdatum;
	}

	public void setMindesthaltbarkeitsdatum(Date mindesthaltbarkeitsdatum) {
		this.mindesthaltbarkeitsdatum = mindesthaltbarkeitsdatum;
	}

	@Column(name = "einzelpreis_einer_ve", nullable = false, scale = 0)
	public double getEinzelpreisEinerVe() {
		return this.einzelpreisEinerVe;
	}

	public void setEinzelpreisEinerVe(double einzelpreisEinerVe) {
		this.einzelpreisEinerVe = einzelpreisEinerVe;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "waren")
	public Set<Warenausgang> getWarenausgangs() {
		return this.warenausgangs;
	}

	public void setWarenausgangs(Set<Warenausgang> warenausgangs) {
		this.warenausgangs = warenausgangs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "waren")
	public Set<Wareneingang> getWareneingangs() {
		return this.wareneingangs;
	}

	public void setWareneingangs(Set<Wareneingang> wareneingangs) {
		this.wareneingangs = wareneingangs;
	}

}
