package at.erplight.model;

// Generated 13.11.2014 22:13:18 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Wareneingang generated by hbm2java
 */
@Entity
@Table(name = "wareneingang", schema = "public")
public class Wareneingang implements java.io.Serializable {

	private int warenEinId;
	private Waren waren;
	private EingangsLieferung eingangsLieferung;
	private Integer warenposten;
	private Double angekundigteVeEingang;
	private Double anzahlDerVeEingang;
	private Double gesamtgewichtEingang;

	public Wareneingang() {
	}

	public Wareneingang(int warenEinId, Waren waren,
			EingangsLieferung eingangsLieferung) {
		this.warenEinId = warenEinId;
		this.waren = waren;
		this.eingangsLieferung = eingangsLieferung;
	}

	public Wareneingang(int warenEinId, Waren waren,
			EingangsLieferung eingangsLieferung, Integer warenposten,
			Double angekundigteVeEingang, Double anzahlDerVeEingang,
			Double gesamtgewichtEingang) {
		this.warenEinId = warenEinId;
		this.waren = waren;
		this.eingangsLieferung = eingangsLieferung;
		this.warenposten = warenposten;
		this.angekundigteVeEingang = angekundigteVeEingang;
		this.anzahlDerVeEingang = anzahlDerVeEingang;
		this.gesamtgewichtEingang = gesamtgewichtEingang;
	}

	@Id
	@Column(name = "waren_ein_id", unique = true, nullable = false)
	public int getWarenEinId() {
		return this.warenEinId;
	}

	public void setWarenEinId(int warenEinId) {
		this.warenEinId = warenEinId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "waren_id", nullable = false)
	public Waren getWaren() {
		return this.waren;
	}

	public void setWaren(Waren waren) {
		this.waren = waren;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "liefer_ein_id", nullable = false)
	public EingangsLieferung getEingangsLieferung() {
		return this.eingangsLieferung;
	}

	public void setEingangsLieferung(EingangsLieferung eingangsLieferung) {
		this.eingangsLieferung = eingangsLieferung;
	}

	@Column(name = "warenposten")
	public Integer getWarenposten() {
		return this.warenposten;
	}

	public void setWarenposten(Integer warenposten) {
		this.warenposten = warenposten;
	}

	@Column(name = "angekundigte_ve_eingang", precision = 17, scale = 17)
	public Double getAngekundigteVeEingang() {
		return this.angekundigteVeEingang;
	}

	public void setAngekundigteVeEingang(Double angekundigteVeEingang) {
		this.angekundigteVeEingang = angekundigteVeEingang;
	}

	@Column(name = "anzahl_der_ve_eingang", precision = 17, scale = 17)
	public Double getAnzahlDerVeEingang() {
		return this.anzahlDerVeEingang;
	}

	public void setAnzahlDerVeEingang(Double anzahlDerVeEingang) {
		this.anzahlDerVeEingang = anzahlDerVeEingang;
	}

	@Column(name = "gesamtgewicht_eingang", precision = 17, scale = 17)
	public Double getGesamtgewichtEingang() {
		return this.gesamtgewichtEingang;
	}

	public void setGesamtgewichtEingang(Double gesamtgewichtEingang) {
		this.gesamtgewichtEingang = gesamtgewichtEingang;
	}

}
